# Generated by Django 5.2.8 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الشريك بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم الشريك بالإنجليزية')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('country_ar', models.CharField(max_length=100, verbose_name='الدولة بالعربية')),
                ('country_en', models.CharField(max_length=100, verbose_name='الدولة بالإنجليزية')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partnerships/', verbose_name='الشعار')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شراكة',
                'verbose_name_plural': 'الشراكات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='صورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
