# Generated by Django 5.2.8 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الفرع بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم الفرع بالإنجليزية')),
                ('branch_type', models.CharField(choices=[('main', 'المقر الرئيسي'), ('regional', 'مكتب إقليمي'), ('partner', 'شريك استراتيجي')], max_length=20, verbose_name='نوع الفرع')),
                ('country_ar', models.CharField(max_length=100, verbose_name='الدولة بالعربية')),
                ('country_en', models.CharField(max_length=100, verbose_name='الدولة بالإنجليزية')),
                ('city_ar', models.CharField(max_length=100, verbose_name='المدينة بالعربية')),
                ('city_en', models.CharField(max_length=100, verbose_name='المدينة بالإنجليزية')),
                ('address_ar', models.TextField(verbose_name='العنوان بالعربية')),
                ('address_en', models.TextField(verbose_name='العنوان بالإنجليزية')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الشركة بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم الشركة بالإنجليزية')),
                ('slogan_ar', models.CharField(max_length=200, verbose_name='الشعار بالعربية')),
                ('slogan_en', models.CharField(max_length=200, verbose_name='الشعار بالإنجليزية')),
                ('about_ar', models.TextField(verbose_name='نبذة عن الشركة بالعربية')),
                ('about_en', models.TextField(verbose_name='نبذة عن الشركة بالإنجليزية')),
                ('vision_ar', models.TextField(verbose_name='الرؤية بالعربية')),
                ('vision_en', models.TextField(verbose_name='الرؤية بالإنجليزية')),
                ('mission_ar', models.TextField(verbose_name='الرسالة بالعربية')),
                ('mission_en', models.TextField(verbose_name='الرسالة بالإنجليزية')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='الشعار')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فيديو الصفحة الرئيسية')),
            ],
            options={
                'verbose_name': 'معلومات الشركة',
                'verbose_name_plural': 'معلومات الشركة',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قيمة أساسية',
                'verbose_name_plural': 'القيم الأساسية',
                'ordering': ['order'],
            },
        ),
    ]
