# Generated by Django 5.2.8 on 2026-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط إنستجرام'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط لينكد إن'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط منصة إكس (تويتر)'),
        ),
    ]
